project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    # Comments
    comments:
      hypothesis: true

    theme:
      light: sass/light.scss
      dark: sass/dark.scss

    email-obfuscation: javascript

execute:
  freeze: true
